service: nversary

frameworkVersion: '2'

plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-1
  lambdaHashingVersion: 20201221
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 'ssm:GetParameter'
          Resource:
            Fn::Sub: "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter${env:SSM_PARAMETER_NAME}"
        - Effect: 'Allow'
          Action:
            - 's3:GetObject'
          Resource:
            - "arn:aws:s3:::${env:PEOPLE_S3_BUCKET}/${env:PEOPLE_S3_KEY}"

functions:
  nversaryGreeter:
    handler: handler.greeter
    description: Sends work anniversary greetings to Slack channel. Runs daily.
    timeout: 300
    events:
      - schedule: cron(50 3 * * ? *)
    environment:
      PEOPLE_S3_BUCKET: ${env:PEOPLE_S3_BUCKET}
      PEOPLE_S3_KEY: ${env:PEOPLE_S3_KEY}
      SSM_PARAMETER_NAME: ${env:SSM_PARAMETER_NAME}
