service:
  name: nversary

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1

functions:
  nversaryGreeter:
    handler: handler.greeter
    events:
    - schedule: cron(50 3 * * ? *)
    environment:
      PEOPLE_S3_URL: TODO
      SSM_PARAMETER_NAME: TODO
